project:
  type: book
  output-dir: ../../docs
  resources:
    - favicon.png 
    - "**/*.gif"

website:
  site-url: https://colacaos.github.io/ColaCAOS
  favicon: https://colacaos.github.io/ColaCAOS/favicon.png

book:
  title: "Estudio del Caos en sistemas f铆sicos y su relaci贸n con la predicci贸n meteorol贸gica"
  author: "Rub茅n Torre Merino"
  chapters:
    - part: "Introducci贸n"
      chapters:
        - intro.qmd
        - index.qmd
        - objetivos.qmd
        - resultados.qmd

    - part: "El Caos a trav茅s de la Funci贸n Log铆stica"
      chapters:
        - 01-logistica/mapa-logistico.qmd
        - 01-logistica/cobweb.qmd
        - 01-logistica/puntos-fijos.qmd
        - 01-logistica/analisis.qmd
        - 01-logistica/generico.qmd
        - 01-logistica/estable.qmd
        - 01-logistica/bifurcaciones.qmd
        - 01-logistica/simulacion.qmd
        - 01-logistica/Caos.qmd
        - 01-logistica/lyapunov.qmd
        - 01-logistica/criterio.qmd

    - part: "El Caos en vivo: El p茅ndulo doble"
      chapters:
        - 02-pendulo-doble/doble.qmd
        - 02-pendulo-doble/simulaciones.qmd
        - 02-pendulo-doble/fractal.qmd
        - 02-pendulo-doble/bifurcacionesPendulo.qmd
        - 02-pendulo-doble/estadisticas.qmd
        - 02-pendulo-doble/experimentos.qmd

    - part: "La Meteorolog铆a y el Caos"
      chapters:
        - 03-meteorologia/meteorologia.qmd
        - 03-meteorologia/calculolyapunov.qmd
        - 03-meteorologia/predicciones.qmd
        - 03-meteorologia/Aemet.qmd

    - part: "El Clima y el Caos"
      chapters:
        - 04-clima/introclima.qmd
        - 04-clima/atractor.qmd
        - 04-clima/rapido.qmd
        - 04-clima/evaluacion.qmd
        - 04-clima/caosclima.qmd

    - part: "Mi sistema ca贸tico"
      chapters:
        - 05-experimentos/intro.qmd
        - 05-experimentos/funcionamientoCaotico.qmd
        - 05-experimentos/test.qmd
    
    - part: "Determinismo y Caos"
      chapters:
        - 06-filosofia/determinismo01.qmd
        - 06-filosofia/determinismo02.qmd
        - 06-filosofia/determinismo03.qmd
        - 06-filosofia/determinismo04.qmd
        - 06-filosofia/determinismo05.qmd
        - 06-filosofia/determinismo06.qmd
        - 06-filosofia/determinismo07.qmd



format:
  html:
    theme: cosmo
    toc: true            # sidebar jer谩rquica
    toc-depth: 2         # hasta niveles ## 
    number-sections: true
    math: katex
    include-in-header:
      text: |
        <link rel="icon" type="image/png" href="https://colacaos.github.io/ColaCAOS/favicon.png">
  pdf:
    pdf-engine: xelatex
    keep-tex: true
    toc: true
    number-sections: true
    papersize: a4
    geometry:
      - margin=2.5cm
    fontsize: 11pt
    include-in-header: |
      \usepackage{amsmath}
      \usepackage{scrhack}
      \usepackage{newunicodechar}
      \newunicodechar{}{\ensuremath{\Rightarrow}}
      \newunicodechar{}{\ensuremath{\ge}}
      \newunicodechar{}{\ensuremath{\delta}}
      \newunicodechar{}{\ensuremath{\theta}}
      \allowdisplaybreaks
      \makeatletter
      \DeclareOldFontCommand{\rm}{\normalfont\rmfamily}{\mathrm}}
      \DeclareOldFontCommand{\bf}{\normalfont\bfseries}{\mathbf}}
      \DeclareOldFontCommand{\it}{\normalfont\itshape}{\mathit}}
      \DeclareOldFontCommand{\tt}{\normalfont\ttfamily}{\mathtt}}
      \DeclareOldFontCommand{\sc}{\normalfont\scshape}{\@nomath\sc}}
      \makeatother