project:
  type: default
  output-dir: ../../docs/slides

lang: es
link-citations: true

execute:
  freeze: auto
  echo: false
  warning: false
  message: false

format:
  revealjs:
    title-slide: false
    theme: [default]
    slide-number: true
    transition: fade
    center: false
    width: 1400
    height: 800
    margin: 0.06
    css: ["assets/css/theme.css"]
    embed-resources: true
  pptx:
    keep-relative-images: true

resources:
  - assets/**
  - demos/**
  - videos/**
  - img/**

metadata-files:
  - assets/meta/common.yml
